"""add_rendimiento_deportivo_remove_perf_from_perfil

Revision ID: 794951b2cc7b
Revises: fd756f3aa6ee
Create Date: 2026-04-20 22:44:14.480171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794951b2cc7b'
down_revision: Union[str, Sequence[str], None] = 'fd756f3aa6ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil', 'bloqueo')
    op.drop_column('perfil', 'envergadura')
    op.drop_column('perfil', 'remate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('remate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('perfil', sa.Column('envergadura', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('perfil', sa.Column('bloqueo', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
