"""add_performance_fields

Revision ID: fd756f3aa6ee
Revises: f9846f33d104
Create Date: 2026-04-20 22:19:55.636351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd756f3aa6ee'
down_revision: Union[str, Sequence[str], None] = 'f9846f33d104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('remate', sa.Float(), nullable=True))
    op.add_column('perfil', sa.Column('bloqueo', sa.Float(), nullable=True))
    op.add_column('perfil', sa.Column('envergadura', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil', 'envergadura')
    op.drop_column('perfil', 'bloqueo')
    op.drop_column('perfil', 'remate')
    # ### end Alembic commands ###
